
$CPAN::Config = {
  'build_cache' => q[64],
  'build_dir' => q[/home/virtwww/w_avtoserviskafe8_945ed433/.cpan/build],
  'cache_metadata' => q[1],
  'cpan_home' => q[/home/virtwww/w_avtoserviskafe8_945ed433/.cpan],
  'dontload_hash' => {  },
  'ftp' => q[],
  'ftp_proxy' => q[],
  'getcwd' => q[cwd],
  'gpg' => q[],
  'gzip' => q[/bin/gzip],
  'histfile' => q[/home/virtwww/w_avtoserviskafe8_945ed433/.cpan/histfile],
  'histsize' => q[100000],
  'http_proxy' => q[],
  'inactivity_timeout' => q[0],
  'index_expire' => q[1],
  'inhibit_startup_message' => q[0],
  'keep_source_where' => q[/home/virtwww/w_avtoserviskafe8_945ed433/.cpan/sources],
  'links' => q[/usr/bin/links],
  'lynx' => q[/usr/bin/lynx],
  'make' => q[/usr/bin/make],
  'make_arg' => q[-j9],
  'make_install_arg' => q[-j9],
  'makepl_arg' => q[PREFIX=~/perl],
  'ncftp' => q[],
  'ncftpget' => q[],
  'no_proxy' => q[],
  'pager' => q[/usr/bin/less],
  'prerequisites_policy' => q[ask],
  'scan_cache' => q[atstart],
  'shell' => q[/bin/bash],
  'tar' => q[/usr/bin/tar],
  'term_is_latin' => q[1],
  'unzip' => q[/usr/bin/unzip],
  'urllist' => [],
  'wget' => q[/usr/bin/wget],
};
1;
__END__
