<?php
// module/Album/view/album/album/index.phtml:

$title = 'ООО "Представительство TECH" - Главная';
$this->headTitle($title);
?>

<div class="center_index">
	<div style="background: powderblue; height: 185px; box-shadow: 0px 0px 10px #666;">
		<!---------------------------------Хит продаж----------------------------->
		<div class="arrow_hit left_arr" onclick="hit_left();" style="margin-left: 100px;">
			<img src="/images/arrow_left.png" />
		</div>
		<div class="hit_prod">
			<?php
			foreach ($hitauto as $key => $ha) {
				if($key == 0) {
					echo '<div id="'. $key .'" class="hit_prod_text">';
					echo '<a>Хит продаж</a>';
					echo '<a>' . $ha->title .'</a>';
					echo '</div>';
					echo '<a id="'. $key .'" class="hit_link" style="display:none; " href="/catalog/product/' . $ha->id . '"></a>';
					echo '<img id="'. $key .'" src="/images/' . $ha->image . '">';
				} else {
					echo '<div id="'. $key .'" class="hit_prod_text" style="opacity:0;">';
					echo '<a>Хит продаж</a>';
					echo '<a>' . $ha->title .'</a>';
					echo '</div>';
					echo '<a id="'. $key .'" class="hit_link" style="display:none; " href="/catalog/product/' . $ha->id . '"></a>';
					echo '<a class="hit_link_up" href=""><img id="'. $key .'" src="/images/' . $ha->image . '" style="opacity:0;"></a>';
				}
			}
			?>

		</div>
		<div class="arrow_hit right_arr" onclick="hit_right();">
			<img src="/images/arrow_right.png" />
		</div>
		<!---------------------------------/Хит продаж----------------------------->

		<!---------------------------------Фирмы----------------------------->
		<div class="arrow_hit left_arr" onclick="firm_left();" style="margin-left: 250px;">
			<img src="/images/arrow_left.png" />
		</div>
		<div class="firm_prod">
			<?php
			foreach ($firms_all as $key => $ha) {
				if($key == 0) {
					echo '<div id="'. $key .'" class="firm_prod_text">';
					echo '<a>Компания</a>';
					echo '<a>' . $ha['title'] .'</a>';
					echo '</div>';
					echo '<a id="'. $key .'" class="firm_link" style="display:none; " href="/catalog' . $ha['link'] . '"></a>';
					echo '<img id="'. $key .'" src="/images/' . $ha['image'] . '">';
				} else {
					echo '<div id="'. $key .'" class="firm_prod_text" style="opacity:0;">';
					echo '<a>Компания</a>';
					echo '<a>' . $ha['title'] .'</a>';
					echo '</div>';
					echo '<a id="'. $key .'" class="firm_link" style="display:none; " href="/catalog' . $ha['link'] . '"></a>';
					echo '<a class="firm_link_up" href=""><img id="'. $key .'" src="/images/' . $ha['image'] . '" style="opacity:0;"></a>';
				}
			}
			?>

		</div>
		<div class="arrow_hit right_arr" onclick="firm_right();">
			<img src="/images/arrow_right.png" />
		</div>
		<!---------------------------------/Фирмы----------------------------->
	</div>
	<!---------------------------------Категории----------------------------->
<!--	<div class="comp_logos"></div>-->
	<div class="clearfix"></div>
	<ul id="gal_c" style="list-style: none; margin: 30px 0 50px 55px; background-color: lightblue;">
		<?php
		foreach($cat_list as $a) {
			?>
			<li style='width: 250px; margin: 7px; height: 150px;  cursor: pointer; box-shadow: 0px 0px 10px #666; display: inline-block; float: left; border-radius: 5px;'>
				<img onclick='gotoHref("<?=$a["link"]?>");' width="250px" height="150px" src="/images/<?=$a['image']?>" style="border-radius: 5px; height: 150px;" onmouseover="imgShow(this);" onmouseout="imgHide(this);">
				<a href="/catalog<?=$a['link']?>" style="text-decoration:none; font-size: 12px; margin-top: -30px; opacity: 0.8; display: block; vertical-align: bottom; width: 250px;height: 30px; background: lightskyblue; z-index: 1; position: absolute; color: #000; text-shadow: 1px 1px 4px #fff; text-align: center; line-height: 24px; border-bottom-left-radius: 5px; border-bottom-right-radius: 5px;"><?=$a['title']?></a>
			</li>
		<?php
		};
		?>
	</ul>
	<!---------------------------------/Категории----------------------------->


	<div class="clearfix"></div>
<!--	-------------------------------Шары----------------------------->
		<div class="circles">
			<ul class="ch-grid">
				<li>
					<div class="ch-item ch-img-1">
						<div class="ch-info">
							<h3>Качесвенные услуги. Быстро</h3>
						</div>
					</div>
				</li>
				<li>
					<div class="ch-item ch-img-2">
						<div class="ch-info">
							<h3>Накопительные скидки до 15%!</h3>
						</div>
					</div>
				</li>
				<li>
					<div class="ch-item ch-img-3">
						<div class="ch-info">
							<h3>до 400 000 рублей за 15 минут на всё оборудование</h3>
						</div>
					</div>
				</li>
			</ul>
		</div>
	<!---------------------------------/Шары----------------------------->
	<div class="clearfix" style="margin-bottom: 30px;"></div>

	<!---------------------------------Текстово-графические блоки перед футером------------------------------------->
	<div class="main_map_left"></div>
	<div class="phone"></div>
	<ul class="afterphone">
		<li>
			<h1>Позвонить или подъехать к нам в офис:</h1>
			<h2>Иноземцево,<br> Гагарина дом 171 "А"</h2>
			Наш менеджер поможет  определиться какие автомобили вы собираетесь обслуживать, для выбора оптимального варианта : цен и качество .Изучив    достоинства  и различие  моделей  Вы сможете купить то, что Вам действительно необходимо.
		</li>
		<li>У клиента всегда должна быть альтернатива выбора по цене, удобству работы, скорости работы и качеству, поэтому мы  11 лет  продаем  оборудование премиум класса : США, Италии  так и средний уровень, и проверенное  нами  лично Россия, Китай, Корея.
			<br><br>Нет ни единого города в Ставропольском крае, где бы  ни стояли сервисы  с  оборудованием,  установленным нашей технической службой.</li>
		<li>Чеченская Республика , Кабардино-Балкарская Республика, Дагестан, Ингушетия, Осетия, Карачаево-Черкесская Республика, Краснодарский край и Ростовская область, Омск, Белгород, Россошь , Брянск, Ханты-Мансийск.
			<br><br>Оборудование  для обслуживания  грузового и легкового  транспорта помогает Вам в жизни.</li>
		<li class="slogan">
			<p>Качество Нашего товара - Залог вашего успеха</p><br><br>
			<a>Оборорудование для достойнейших. <br> Цены и <span>скидки до 15%</span> <br>на оборудование<br> приятно удивят Вас!</a>
			<div class="perc15"></div>
		</li>
	</ul>

	<p class="plodotv">
		Плодотворного сотрудничества, добра и процветания!<br><br>
		Директор: <span>Купцова Светлана Георгиевна</span>
	</p>
		<div class="clearfix"></div>
	<!---------------------------------/Текстово-графические блоки перед футером------------------------------------->
</div>

<script>

	function imgShow (obj) {
		$(obj).parent('li').css({"box-shadow": "0px 0px 20px #000"});
	}
	function imgHide (obj) {
		$(obj).parent('li').css({"box-shadow": "0px 0px 10px #666"});
	}
	function gotoHref(link) {
		window.location.href = '/catalog' + link;
	}
</script>