<?php
// module/Album/view/album/album/list.phtml:

$title = 'ООО "Представительство TECH" - ' . $category["title"];
$this->headTitle($title);
?>

<div class="center_catalog">

	<!---------------------------------Левое меню----------------------------->
	<div class="left_menu">
		<h3>КАТАЛОГ</h3>
		<ul>
			<?php
			foreach ($cat_list as $key => $cl) {
				if($key<7){
					echo '<li><a href="/catalog' . $cl['link'] . '">' . $cl['title'] . '</a></li>';
				}
			}
			?>
			<li style=" margin-top: 5px;"><a href="/catalog" style="color: #fff;"><b>Весь каталог...</b></a></li>
		</ul>
	</div>
	<!---------------------------------/Левое меню----------------------------->

	<div class="breadcrumb_auto"><a href="/catalog">Каталог</a> &larr; </div>

	<div class="main_left_menu_text_cat">
		<h3 id='category_title'><?=$category['title'] ?></h3>
		<br>
		<p id="category_desc"><?=$category['desc'] ?></p>
	</div>

	<!---------------------------------Галерея----------------------------->
	<div class="hit_prod" style="margin-left: 20px;">
		<?php
				echo '<img src="/images/' . $category['image'] . '">';
		?>
	</div>
	<!---------------------------------/Галерея----------------------------->

	<div style="clear: both"></div>
	<?php
	if(isset($firm_res)) {
		echo '<ul class="firm_gal">';
			foreach ($firm_res as $f_key => $f_item) {
				if($f_key < 6) {
					echo '<li>';
					echo '<img src="/images/' . $f_item['image'] . '" onclick="firm_toggle('. $f_item['id'] .');">';
					echo '</li>';
				}
			}
		echo '</ul>';
	}
	?>
	<hr/>

	<div id="list_center">
		<!---------------------------------Центр---------------------------------->
		<?php
			if(isset($product_all)) {
				foreach($product_all as $key => $ha) {
					if(isset ($ha['firm_id'])) {
						echo '<ul class="category_list firm_' . $ha['firm_id'] . '">';
					} else {
						echo '<ul class="category_list">';
					}
					echo '<li>';
					echo "<h3>{$ha['title']}</h3>";
					echo '<a href="/catalog' . $ha['link'] . '">Перейти...</a>';
					echo '</li>';
					echo '<li>';
					echo "<h4>{$ha['desc']}</h4>";
					echo '</li>';
					echo '<li>';
					if ($ha['image'] != '') {
						echo '<img src="/images/' . $ha['image'] .'">';
					} else {
						echo '<img style="background: #ccc;" src="/images/menu_logo_TK.png">';
					}
					echo '</li>';
					echo '</ul>';
				}
			} else {
				echo '<a style="display: block; height: 50px; text-align: center;">На данный момент оборудование отсутствует!</a>';
			}
		?>
		<!---------------------------------/Центр---------------------------------->
	</div>
</div>