<?php echo $this->doctype(); ?>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle() ?>

		<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

		<!-- Le styles -->
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
						->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
						->prependStylesheet($this->basePath() . '/css/style.css')
						->prependStylesheet($this->basePath() . '/css/auto.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

		<!-- Scripts -->
		<?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
									  ->prependFile($this->basePath() . '/js/bootstrap.min.js')
									  ->prependFile($this->basePath() . '/js/auto.js')
									  ->prependFile($this->basePath() . '/js/jquery.min.js')
									  ->prependFile($this->basePath() . '/ckeditor/ckeditor.js')?>

	</head>
	<body>
	<script type="text/javascript">

	</script>
		<div class="main">
			<div class="container" style="width: 1170px;">
				<div style='background: url("/images/up_bg.jpg"); width: 1170px;height: 180px;'>
					<div style="width: 700px; color: #fff; text-shadow: 0px 0px 15px #000; text-align: left;  margin-left: 10px; font-family: ft40; display: inline-block;">
						<p style=" padding-top: 10px; font-weight: bold; margin-bottom: 5px;font-size: 26px; margin-top: 0;">ООО "Представительство Технологий", ИП Купцова С.Г.</p>
						<p style=" font-weight: bold; padding: 0; margin: 0;font-size: 26px;">Качество нашего товара - залог вашего успеха!</К></p>
						<p style="font-weight: bold; margin-left: 60px; margin-top: 10px;">
							Ставропольский край,<br>
							пос.Иноземцево, ул.Гагарина 171 "А"<br>
							тел\факс: +7(87932)-5-40-44<br>
							телефон сот.: +7(928)363-70-91, +7(9624)466-911.<br>
						</p>
					</div>
					<div style="display: inline-block; width: 300px; margin-left: 80px; color: lightblue; text-shadow: 0px 0px 10px #ccc; vertical-align: top; margin-top: 30px;">
						<img width="300" src="/images/logo_tech.png">
					</div>
				</div>
				<div class="menu_auto">
<!---------------------------------Меню----------------------------->
					<div class="menu_block">
						<a href="/">Главная</a>
						<a href="/onas">О нас</a>
						<a href="/catalog">Каталог</a>
						<a href="">Новинки</a>
						<a href="/discounts">Скидки</a>
						<a href="/contacts">Контакты</a>
					</div>
				</div>
<!---------------------------------/Меню----------------------------->

<!---------------------------------Слайдер----------------------------->
				<div class="top_slider">
					<ul>
						<li class="slider_arrow_left" onclick="top_slider_left();"></li>
						<li class="slider_image">
							<img id="sl_i_1" src="/images/modena_mo_230mr.png">
<!--							<img style="margin-left: -150px; opacity: 0;" id="sl_i_2" src="/images/launch_kds_5k.png">-->
							<img style="margin-left: -150px; opacity: 0;" id="sl_i_2" src="/images/giuliano_s_112f.png">
							<img style="margin-left: -150px; opacity: 0;" id="sl_i_3" src="/images/titan_54_00_bridge.png">
							<img style="margin-left: -150px; opacity: 0;" id="sl_i_4" src="/images/hunter_gsp9200.png">
							<img style="margin-top:-100px; margin-left: -200px; opacity: 0;" id="sl_i_5" src="/images/siver_e.png">
						</li>
						<li style="	vertical-align: top;">
							<div id="sl_txt_1" class="slider_text">
								<h1>Автомобильный <br> подъемник</h1>
								<h2>MO-230MR/240MR</h2>
								<p>Автомобильный двухстоечный подъемник компании <b style="color: #ff0000;">Modena</b> c гарантией в 3 года и подобной информацией по установке.<br> Лучшее решение для автосервиса.</p>
							</div>
<!--							<div style="opacity: 0;" id="sl_txt_2" class="slider_text">-->
<!--								<h1>Компьютерный стенд <br> "сход-развал"</h1>-->
<!--								<h2>Launch КДС 5К</h2>-->
<!--								<p>Высокоточный и высоконадежный измерительный комплексм для проведения качественных измерений в процессе регулирования углов установки колес.</p>-->
<!--							</div>-->
							<div style="opacity: 0;" id="sl_txt_2" class="slider_text">
								<h1>Шиномонтажный стенд</h1>
								<h2>GIULIANO S 112F(GT)</h2>
								<p>Размер диска(снаружи) - 12-22"<br> Усилие при отжатии покрышки 2,5 тонны<br>Двигатель 380В, 0.55 кВт<br>Монтажный стол скругленный<br>Габариты в упаковке 108х94х170 см<br>Вес 158кг(GT 213кг)</p>
							</div>
							<div style="opacity: 0;" id="sl_txt_3" class="slider_text">
								<h1>Стенд для <br>правки дисков</h1>
								<h2>Titan 54-00 Bridge</h2>
								<p>Стенд(станок) для правки колесных дисков предназначен для реставрации легкосплавных, кованых и стальных дисков, диаметром от 10 до 24 дюймов.</p>
							</div>
							<div style="opacity: 0;" id="sl_txt_4" class="slider_text">
								<h1>Балансировочный стенд <br>с LCD-монитором</h1>
								<h2>Hunter GSP9200</h2>
								<p>Hunter GSP9200 представляет собой компьютеризированный балансировочный стенд с LCD-монитором и автоматическим вводом всех трех параметров колеса.</p>
							</div>
							<div style="opacity: 0;" id="sl_txt_5" class="slider_text">
								<h1>Универсальная система для рихтовки кузовов</h1>
								<h2>SIVER "E"</h2>
								<p>Стенд для правки кузовов SIVER "E" предназначен для восстановления аварийных кузовов транспортных средств. Оборудование имеет сертификат соответствия требованиям безопасности, сертификат СЕ и пожизненную гарантию на платформу.</p>
							</div>
						</li>
						<li class="slider_arrow_right" onclick="top_slider_right();"></li>
					</ul>

				</div>
<!---------------------------------/Слайдер----------------------------->

				<div class="center">
					<div style="background: #fff;">
						<?php echo $this->content; ?>
					</div>
				</div>

				<div class="footer">
					<div class="footer_up"></div>
					<p style="margin-left: 330px; float: left; color: #b7dae8; font-size: 14px; font-family: Corbil; margin-right: 450px">Задайте вопрос</p>
					<form action="" class="footer_form">
						<div style="display: inline-block; margin-left: 270px;">
							<label>Ф.И.О.</label>
							<label>e-mail</label>
							<label>Тема</label>
						</div>
						<div style="display: inline-block;">
							<input id="mail_name" name="mail_name"><br>
							<input id="mail_email" name="mail_email"><br>
							<input id="mail_topic" name="mail_topic"><br>
						</div>
						<div style="display: inline-block; vertical-align: top;">
							<textarea id="mail_text" name="mail_text" ></textarea><br>
							<p style=" font-family: Corbil;font-size: 12px; margin: 10px 0 0 210px; cursor: pointer;" onclick="mail_submit();">Отправить</p>
						</div>
					</form>
				</div>
				<footer >
				</footer>
			</div> <!-- /container -->
		</div>

		<?php echo $this->inlineScript() ?>
	<script>
		$(document).ready(function()
		{
			var editor = CKEDITOR.replace('q_text',
					{
						filebrowserBrowseUrl : '/ckeditor/pdw_file_browser/index.php?editor=ckeditor',
						filebrowserImageBrowseUrl : '/ckeditor/pdw_file_browser/index.php?editor=ckeditor&filter=image',
						filebrowserFlashBrowseUrl : '/ckeditor/pdw_file_browser/index.php?editor=ckeditor&filter=flash',
						filebrowserUploadUrl: '/uploader/upload.php',
						toolbar: 'Full'
					});
		});
	</script>
	</body>
</html>
